default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: mark_noce_development


test:
  <<: *default
  database: mark_noce_test

production:
  <<: *default
  database: mark_noce_production
  username: mark_noce
  password: <%= ENV['MARK_NOCE_DATABASE_PASSWORD'] %>
